############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################
# This plugin was created by: 
# Carlgo11 http://www.carlgo11.com/
# Psgs http://www.psgs.tk/
# Cabbex 
# Get in touch with us:
#
# Join our irc: http://bit.ly/cmdbouncerirc
# 
 
############################################################
# +------------------------------------------------------+ #
# |                  General Settings                    | #
# +------------------------------------------------------+ #
############################################################

# Does this plugin not work? Set "debug" to true and pastie your server.log to an developer
# true/false
debug: false

# Do you want the plugin to update automaticly when a new version is avible? (Recommended: 'true')
auto-update: true

# Backup the current config and replace it with a new one when a new version of CommandBouncer is downloaded.
update-config: false

# When seeking assistance via /CommandBouncer support/report should the plugin upload your latest.log? (Recommended: 'true')
send-log: true


############################################################
# +------------------------------------------------------+ #
# |                       Settings                       | #
# +------------------------------------------------------+ #
############################################################

# [Instructions here]
disabled-worlds:
- a_disabled_world
- another_disabled_world

# [Instructions here]
ignored-players:
- a_ignored_user
- anminecrafter
# Do you want to disable the incomming message when a command matches a commnad listed below?
# Example: player types /op, cmd is set to disable = the incomming message won't be blocked. 
# If cmd is not listed below it will be set to true by defualt.

disabled-commands:
- cmd1

############################################################
# +------------------------------------------------------+ #
# |                   Listen Commands                    | #
# +------------------------------------------------------+ #
############################################################

# Enter the commands you want the plugin to listen on use the same number on the listening command as on the bouncer command!
# EXAMPLE: cmd1: hi


############################################################
# +------------------------------------------------------+ #
# |                   Bounce Commands                    | #
# +------------------------------------------------------+ #
############################################################

# Enter the commands that you want the plugin to execute when a player types the given command

# EXAMPLE: 
# cmd1:
# - say hello %player%

