main: commandbouncer.carlgo11.CommandBouncer.CommandBouncer
name: CommandBouncer
version: 0.1
author: Carlgo11, Cabbex, psgs
description: This plugin sends a command that's set in the config, when a user types a certain command.
commands:
  CommandBouncer:
    aliases: [cmdbnc, ccommandbouncer]
    description: Main command of CommandBouncer
permissions:
  CommandBouncer.*:
    default: op
    description: Give players permission to use everything
  CommandBouncer.listen.*:
    default: op
    description: Plugin will listen on every command the player executes
  commandbouncer.cmd.commandbouncer:
    default: op
    description: Give players permission to use /commandbouncer
  commandbouncer.cmd.commandbouncer.reload:
    default: op
    description: Give players permission to use /commandbouncer reload
    